export const GET_DATA_PHOTO_REQUEST = 'GET_DATA_PHOTO_REQUEST';
export const GET_DATA_PHOTO_REQUEST_SUCCESS = 'GET_DATA_PHOTO_REQUEST_SUCCESS';
export const GET_DATA_PHOTO_REQUEST_FAILED = 'GET_DATA_PHOTO_REQUEST_FAILED';

export const SEARCH_PHOTO_REQUEST = 'SEARCH_PHOTO_REQUEST';
export const SEARCH_PHOTO_REQUEST_SUCCESS = 'SEARCH_PHOTO_REQUEST_SUCCESS';
export const SEARCH_PHOTO_REQUEST_FAILED = 'SEARCH_PHOTO_REQUEST_FAILED';
export const LOADING = 'LOADING'

export const GET_DETAIL = 'GET_DETAIL';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_FAILED = 'GET_DETAIL_FAILED';
